version: "3"

services:
  app:
    # Build the image using the Dockerfile in the current directory
    build: .
    # Mount the local directory to the container, enabling live code updates during development
    volumes:
      - .:/app
    # Expose the WebSocket port
    ports:
      - "3002:3002"
